### ISSUE TITLE
Typos in the terraform script 

### ISSUE THREAD

**Issue by samiislam** [philips-labs/terraform-hsdp-dicom#3]
In the modules/shared/main.tf:

- on line 7: resource "hsdp_iam_application" "app_diom" -> It should be "app_di**c**om"
- on line 107: application_id = hsdp_iam_application.app_diom.id -> It should be "app_di**c**om"
- on line 173: name         = "Manaing Org - ${var.organization_id}" -> It should be "Mana**g**ing Org"

In the modules/tenant/main.tf:
- on line 7: resource "hsdp_iam_application" "app_diom" -> It should be "app_di**c**om"
- on line 85: application_id = hsdp_iam_application.app_diom.id ->  It should be "app_di**c**om"

**Comment by loafoe** [comment]
@samiislam thanks for reporting this. If you are able to create a pull-request for these changes it will be merged ASAP!

**Comment by khhipparagi** [comment]
Fixed
